### ISSUE TITLE
Dealing with Multiple Accounts for One Person

### ISSUE THREAD

**Issue by nixpulvis** [nuacm/website#65]
There is currently nothing stopping a person from creating many accounts with multiple emails. This causes a problem of having more than one of the same name on the members page.

![screen shot 2013-10-09 at 9 37 59 am](https://f.cloud.github.com/assets/715947/1297731/18cfaa56-30e8-11e3-8f4b-884e4f7b7dbc.png)

**Comment by nixpulvis** [comment]
Thoughts? @ali @joshcaron @aliceyoung9

**Comment by ali** [comment]
Nothing we can really do here. As far as I know there's only one Eric Chin, but I also know there are two distinct Thang Nguyens at CCIS. Our site has no way of knowing which email addresses belong to either one (since those are user-provided).

Shitty solution: on the signup page we can ask "Hey, we already have a {name} on file. Did you already register?"

Another shitty solution: We _could_ force signup with a husky email address, ask for a CCIS handle (remember, we have a few members who _aren't_ CCIS), and then let users log in with either.

**Comment by zack** [comment]
Since we are /Northeastern University/ ACM, I don't think forcing a husky address is too out of line. Personally, I like being able to choose which of my dozen email addresses to use for a given service, but I would support requiring a husky email for this. I don't see the point of dealing with CCIS handles if we go that route.

**Comment by nixpulvis** [comment]
We already have a bunch if non husky emails though. And do we really not want people without husky emails to be unable to signup?

**Comment by zack** [comment]
I don't know. That depends what the point of signing up is. What's the point of signing up?

**Comment by ali** [comment]
It's mostly for us to email our members and track who's paid dues. There's no actual point for a member to log in (at the moment).

**Comment by nixpulvis** [comment]
Yea it's the email newsletters I'm thinking about. 

---

Nathan Lilienthal
@nixpulvis (everywhere)

**Comment by aceyoung9** [comment]
....and those will be managed through Mailchimp and a user can unsubscribe
if he/she wants, yes?

Alice Young

**Comment by nixpulvis** [comment]
Managed through mail chimp yes. But the question is do we require people to use their husky email or any email. I'm not really sure we want to be restricting this to husky.

**Comment by ali** [comment]
How about paid members show up on the roster (no more duplicate names in our roster), and we let anyone sign up with whatever email they want.

**Comment by zack** [comment]
I like that.

**Comment by nixpulvis** [comment]
Ok that sounds good.

---

Nathan Lilienthal
@nixpulvis (everywhere)
